apiVersion: apps/v1
kind: Deployment
metadata:
  name: 28
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops
  template:
    metadata:
      labels:
        app: gitops
    spec:
      containers:
        - name: gitops
          image: docker.io/l3j5g7d9/gitops-go-app:latest
          imagePullPolicy: IfNotPresent
